apiVersion: batch/v1
kind: Job
metadata:
  name: restore-{{ .Values.database.name }}
  labels:
    group: nuodb
    subgroup: job
    database: "{{ .Values.database.name }}"
spec:
  parallelism: 1
  completions: 1
  activeDeadlineSeconds: {{ .Values.restore.timeout }}
  template:
    spec:
{{- if .Values.restore.affinity }}
      affinity:
{{ tpl .Values.restore.affinity . | trim | indent 8 }}
{{- end }}
      containers:
      - name: restore
        image: {{ template "nuodb.image" . }}
        imagePullPolicy: {{ default "" .Values.nuodb.image.pullPolicy | quote }}

        ##
        # call the nuorestore script
        ##
        args:
        - "nuorestore"
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.database.name }}.nuodb.com
              key: database-name
        - { name: NUOCMD_API_SERVER,   value: "{{ template "admin.address" . }}:8888"}
        - { name: NUODB_RESTORE_URL,   value: {{ default ":latest" .Values.restore.backupSet }} }
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/nuodb
        {{- if .Values.admin.tlsCACert }}
        - name: tls-ca-cert
          mountPath: /etc/nuodb/keys/ca.cert
          subPath: {{ .Values.admin.tlsCACert.key }}
        {{- end }}
        {{- if .Values.admin.tlsClientPEM }}
        - name: tls-client-pem
          mountPath: /etc/nuodb/keys/nuocmd.pem
          subPath: {{ .Values.admin.tlsClientPEM.key }}
        {{- end }}
{{- include "nuodb.imagePullSecrets" . | indent 6 }}
      volumes:
      - name: log-volume
        emptyDir: {}
      {{- if .Values.admin.tlsCACert }}
      - name: tls-ca-cert
        secret:
          secretName: {{ .Values.admin.tlsCACert.secret }}
          defaultMode: 0440
      {{- end }}
      {{- if .Values.admin.tlsClientPEM }}
      - name: tls-client-pem
        secret:
          secretName: {{ .Values.admin.tlsClientPEM.secret }}
          defaultMode: 0440
      {{- end }}
      restartPolicy: Never
