apiVersion: v1 
kind: Pod
metadata:
  name: nuodb-dashboard-store
  labels:
    app: monitor
    group:    nuodb
    subgroup: monitoring
    selector: backend
spec:
  containers:
  - name: metrics
    env:
    - { name: INFLUXDB_GRAPHITE_ENABLED,   value: "true"}
    image: {{ template "influxdb.image" . }}
    imagePullPolicy: {{ .Values.influx.image.pullPolicy }}
    ports:
    - { containerPort: 8086, protocol: TCP }
    - { containerPort: 2003, protocol: TCP }
    volumeMounts:
    - name: storage
      mountPath: /var/lib/influxdb
    - name: initdb
      mountPath: /docker-entrypoint-initdb.d/init-nuodb.sh
      subPath: init-nuodb.sh
  dnsPolicy: ClusterFirst
{{- include "influx.imagePullSecrets" . | indent 2 }}
  serviceAccount: default               
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: metricdb
  - name: initdb
    configMap:
      name: nuoca-influxdb-configmap
     # defaultmode: 0744
