kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: {{ template "admin.fullname" . }}
    group: nuodb
    domain: {{ .Values.admin.domain }}
    chart: {{ template "admin.chart" . }}
    release: {{ .Release.Name | quote }}
  name: nuodb-license-file
data:
{{- if .Values.admin.configFiles }}
{{ toYaml .Values.admin.configFiles | indent 2 }}
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "admin.fullname" . }}
    group: nuodb
    domain: {{ .Values.admin.domain }}
    chart: {{ template "admin.chart" . }}
    release: {{ .Release.Name | quote }}
  name: waitscript
data:
{{ (.Files.Glob "files/waitscript").AsConfig | indent 2 }}