---
{{- range $path, $bytes := .Files.Glob "files/dashboards/**.json" }}
{{- $ext :=  ext ($path) }}
{{- $name :=  base ($path) | replace $ext ""}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nuodb-dashboards-{{ $name }}
  labels:
    group:    nuodb
    subgroup: monitoring
data:
{{ ($.Files.Glob (printf "files/dashboards/%s%s" $name $ext)).AsConfig | indent 2 }}
---
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nuodb-dashboard-provisioning
  labels:
    group:    nuodb
    subgroup: monitoring
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: nuodb
        type: influxdb
        access: proxy
        orgId: 1
        url: http://metricdb:8086
        password: ''
        user: ''
        database: 'nuodb'
        basicAuth: false
        basicAuthUser: ''
        basicAuthPassword: ''
        withCredentials: false
        isDefault: true
        jsonData:
          timeInterval: '10s'
        secureJsonData: {}
        version: 1
        editable: false
  nuodb.yaml: |
    apiVersion: 1

    providers:
    - name: 'nuodb'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      updateIntervalSeconds: 3 
      options:
        path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nuoca-influxdb-configmap
  labels:
    app:      monitor
    group:    nuodb
    subgroup: monitoring
data:
  nuoca.yml.template: |+
    ---
    NUOCA_LOGFILE: /var/log/nuodb/nuoca.log

    INPUT_PLUGINS:
    - NuoAdminNuoMon:
        description : Collection from NuoDB engines
        nuocaCollectionName: NuoMon
        api_server:  ${NUOCMD_API_SERVER}
        client_key:  /etc/nuodb/keys/nuocmd.pem
    OUTPUT_PLUGINS:
    - InfluxDB:
        url: http://metricdb:8086/write?db=nuodb
  init-nuodb.sh: |+
    /usr/bin/influx -execute "CREATE DATABASE nuodb WITH DURATION 365d REPLICATION 1 SHARD DURATION 1d NAME nuodbrp"
