{{- if and (.Values.openshift.enabled) (.Values.openshift.enableRoutes) }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: monitor
    group: nuodb
    subgroup: monitoring
  name: dashboard
spec:
  port: { targetPort: 80-tcp }
  to: { kind: Service, name: dashboard, weight: 100 }
  wildcardPolicy: None
{{- end }}