apiVersion: batch/v1
kind: Job
metadata:
  name: restore-{{ .Values.database.name }}
  labels:
    group: nuodb
    subgroup: job
    database: "{{ .Values.database.name }}"
spec:
  parallelism: 1
  completions: 1
  activeDeadlineSeconds: {{ .Values.restore.timeout }}
  template:
    spec:
{{- if .Values.restore.affinity }}
      affinity:
{{ tpl .Values.restore.affinity . | trim | indent 8 }}
{{- end }}
      initContainers:
      - name: archive-clear
        image: {{ template "init.image" . }}
        imagePullPolicy: {{ default "" .Values.busybox.image.pullPolicy | quote }}
        volumeMounts:
        - name: target
          mountPath: /var/opt/nuodb/archive
        command: ["sh", "-c", "rm -rf /var/opt/nuodb/archive/{{ .Values.admin.domain }}/{{ .Values.database.name }}/*"]
      containers:
      - name: nuodb-ce
        image: {{ template "nuodb.image" . }}
        imagePullPolicy: {{ default "" .Values.nuodb.image.pullPolicy | quote }}
        args:
        - "nuodocker"
        - "--api-server"
        - "https://{{ template "admin.address" . }}:8888"
        - "restore"
        - "archive"
        - "--origin-dir"
        - "/var/opt/nuodb/backup/{{ .Values.restore.backupSet }}"
        - "--restore-dir"
        - "/var/opt/nuodb/archive/{{ .Values.admin.domain }}/{{ .Values.database.name }}"
        - "--db-name"
        - "{{ .Values.database.name }}"
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - { name: DB_NAME,             value: "{{ .Values.database.name }}" }
        - { name: NUOCMD_API_SERVER,   value: "{{ template "admin.address" . }}:8888"}
        volumeMounts:
        - name: source
          mountPath: /var/opt/nuodb/backup
        - name: target
          mountPath: /var/opt/nuodb/archive
{{- include "nuodb.imagePullSecrets" . | indent 6 }}
      volumes:
      - name: source
        persistentVolumeClaim:
          claimName: {{ .Values.restore.backupPvc }}
      - name: target
        persistentVolumeClaim:
          claimName: {{ .Values.restore.archivePvc }}
      restartPolicy: Never
