---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "database.fullname" . }}
    group: nuodb
    domain: {{ .Values.admin.domain }}
    chart: {{ template "database.chart" . }}
    release: {{ .Release.Name | quote }}
  name: {{ template "database.fullname" . }}-nuote
data:
{{ (.Files.Glob "files/nuote").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "database.fullname" . }}
    group: nuodb
    domain: {{ .Values.admin.domain }}
    chart: {{ template "database.chart" . }}
    release: {{ .Release.Name | quote }}
  name: {{ template "database.fullname" . }}-nuosm
data:
{{ (.Files.Glob "files/nuosm").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "database.fullname" . }}
    group: nuodb
    domain: {{ .Values.admin.domain }}
    chart: {{ template "database.chart" . }}
    release: {{ .Release.Name | quote }}
  name: {{ template "database.fullname" . }}-nuobackup
data:
{{ (.Files.Glob "files/nuobackup").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "database.fullname" . }}
    group: nuodb
    domain: {{ .Values.admin.domain }}
    chart: {{ template "database.chart" . }}
    release: {{ .Release.Name | quote }}
  name: {{ .Values.database.name }}-restore
data:
  NUODB_AUTO_IMPORT: {{ .Values.database.autoImport.source }}
  NUODB_AUTO_RESTORE: {{ .Values.database.autoRestore.source }}
  NUODB_IMPORT_STRIP_LEVELS: {{ default "1" .Values.database.autoImport.stripLevels | quote }}
  NUODB_RESTORE_STRIP_LEVELS: {{ default "1" .Values.database.autoRestore.stripLevels | quote }}
  NUODB_RESTORE_REQUEST_PREFIX: {{ default "/nuodb/nuosm/database" .Values.nuodb.requestKey }}
  NUODB_BACKUP_KEY: {{ default "/nuodb/nuobackup" .Values.nuodb.latestKey }}
  NUODB_LATEST_BACKUP_PREFIX: {{ default "nuodb-backup/last_created" .Values.nuodb.latestPrefix }}

